# -*- coding: utf-8 -*-
"""find-the-largest-number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXT7qFmMY3DMgPxRQwzDC0WkO-5Xe2sz
"""

say = []
i = 1
while i < 6 :
  say.append(int(input("sayı giriniz : ")))
  i += 1
say.sort()
print('girilen sayıların en büyüğü : ',say[-1])